name: responsi
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.0              # State management
  http: ^0.15.0                 # Networking untuk API requests
  shared_preferences: ^2.0.6    # Penyimpanan data lokal
  intl: ^0.17.0                 # Internasionalisasi
  cached_network_image: ^3.0.0  # Caching gambar dari internet
  flutter_localizations:        # Untuk dukungan lokal bahasa
    sdk: flutter
  json_annotation: ^4.4.0       # Annotation untuk model dari JSON


  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.1.0          # Untuk auto generate code
  json_serializable: ^6.0.1     # Untuk auto-generate model JSON

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
